server:
  port: 8089

spring:
  application:
    name: comment-service
  datasource:
    url: jdbc:postgresql://postgres:5432/comment_db
    username: ${POSTGRES_USER:blog}
    password: ${POSTGRES_PASSWORD:blog}
  flyway:
    enabled: true

blog:
  services:
    article-service-url: http://article-service:8084

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
