server:
  port: 8090

spring:
  application:
    name: stats-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: false

blog:
  services:
    article-service-url: http://localhost:8084

eureka:
  client:
    enabled: false

management:
  metrics:
    tags:
      application: ${spring.application.name:stats-service}
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
