server:
  port: 8085

spring:
  application:
    name: tag-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: false

eureka:
  client:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
